# Generated by Django 4.2.1 on 2023-10-11 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoRepeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular object across whole database', primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('repeat_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('repeat_interval', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('repeat_days', models.CharField(blank=True, max_length=50, null=True)),
                ('repeat_end_date', models.DateField(blank=True, null=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
