# Generated by Django 4.2.1 on 2023-10-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todorepeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todorepeat',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_repeat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todorepeat'),
        ),
    ]
