# Generated by Django 4.2.1 on 2023-10-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todorepeat_repeat_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_repeat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todorepeat'),
        ),
    ]
