# Generated by Django 4.2.1 on 2023-10-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_todo_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorepeat',
            name='todo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeat', to='todo.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_repeat',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_todo', to='todo.todorepeat'),
        ),
    ]
