# Generated by Django 4.1.7 on 2023-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimer',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
