# Generated by Django 4.1.7 on 2023-03-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_tasktimer_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktimer',
            options={'ordering': ['-start_time']},
        ),
    ]
