# Generated by Django 4.1.7 on 2023-03-26 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('time_tracker', '0003_alter_tasktimer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.CreateModel(
            name='ActiveTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular object across whole database', primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.task')),
                ('task_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.tasktimer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
