# Generated by Django 4.1.7 on 2023-03-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_tasktimer_user_activetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='activetask',
            name='task',
        ),
    ]
