# Generated by Django 4.1.7 on 2023-03-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0005_remove_activetask_project_remove_activetask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetask',
            name='user',
        ),
    ]
