# Generated by Django 4.2.1 on 2023-10-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0005_todo_linked_to_todo_urgency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
