# Generated by Django 4.1.7 on 2023-03-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('time_tracker', '0006_remove_activetask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetask',
            name='task_timer',
        ),
        migrations.AddField(
            model_name='activetask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracker.task'),
        ),
        migrations.AddField(
            model_name='activetask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
