# Generated by Django 4.1.7 on 2023-04-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sticky_note', '0001_initial'),
        ('status', '0001_initial'),
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracker.project'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.notestatus'),
        ),
    ]
