# Generated by Django 4.1.7 on 2023-03-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0007_remove_activetask_task_timer_activetask_start_time_and_more'),
        ('sticky_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracker.project'),
        ),
    ]
