# Generated by Django 4.1.7 on 2023-03-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('sticky_note', '0002_stickynote_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.notestatus'),
        ),
    ]
