# Generated by Django 4.1.7 on 2023-04-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_masterstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notestatus',
            name='master_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.masterstatus'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='master_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.masterstatus'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='master_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.masterstatus'),
        ),
    ]
